### ISSUE TITLE
Quo vadis? Future of RestDoc

### ISSUE THREAD

**Issue by hoegertn** [RestDoc/specification#19]
\cc @grncdr @saary @zacstewart

Seeing the development of WADL and Swagger, I think we have to choose between two option.
- Giving up RestDoc and moving to the "winner"
- Enhancing the ecosystem of RestDoc and promoting it actively

I just wanted to hear your thoughts on this topic.

**Comment by grncdr** [comment]
IMO swagger 2 fixed all of the issues I had with swagger 1 that motivated my earlier contribution to restdoc. Declaring this project officially dead, (maybe making a tool to convert from rest doc to swagger 2) seems like the most reasonable course of action

**Comment by saary** [comment]
Same here.
Swagger seems like the choice I would have made looking into this subject
today. So I vote for it as the course of action as well.

**Comment by zacstewart** [comment]
Agreed.

**Comment by hoegertn** [comment]
So, I think that's it.
I will change the website and github repo to reflect the decision.

**Comment by saary** [comment]
Thank you guys and thank you Thorsten for all the effort you put into this
project. It has been an interesting experiment..
